version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: quiz_empire_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: QuizEmpireDb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # Позже сюда добавим Redis для кэша и Hangfire, но для начала хватит БД
  
volumes:
  pgdata: